import "./globals.css";

import type { Metadata } from "next";

import { Sidebar } from "@/components/layout/Sidebar";
import { Topbar } from "@/components/layout/Topbar";
import { inter } from "@/components/ui/fonts";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Providers>
          <Sidebar />
          <Topbar />
          <main className="ml-sidebar pt-topbar min-h-screen text-foreground bg-background">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
