import "./globals.css";

import type { Metadata } from "next";

import { inter } from "@/ui/fonts";
import { Sidebar } from "@/ui/navigation/Sidebar";

import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Providers>
          <Sidebar />
          <main className="ml-sidebar min-h-screen text-foreground bg-background">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
